---
- hosts: all
  become: true
  tasks:
    - name: update apt update_cache
      apt: update_cache=yes cache_valid_time=86400
#- import_playbook: getcontent.yml
- import_playbook: httpd.yml
- import_playbook: mysql.yml
