---
# tasks file for mysql
- name: install mysqldb
  apt: name=mysql-server state=present

- name: install tools
  apt: name={{item}} state=present
  with_items:
    - python-mysqldb
  notify: restart mysql

# If you need to do a case-insensitive search then you can do
# something like below.  The ‘?i’ means it is a case sensitive replace.
# Before 2.3, option 'dest', 'destfile' or 'name'
- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ansible_eth0.ipv4.address}}"
  notify: restart mysql

- name: enable mysql server
  service: name=mysql state=started enabled=yes

- name: create demo database
  mysql_db: name={{mysql_db_name}} state=present

- name: create user
  mysql_user: name={{mysql_user}} password={{mysql_pass}} priv={{mysql_db_name}}.*:ALL host='{{mysql_db_user_host}}' state=present
